# Working Example Configuration
# This configuration uses the provided sample data and can be run immediately

dataset_path: "examples/sample_data.txt"
output_dir: "trained_models/<<group_name>>/<<job_name>>"

assistant_config:
  model_path: "gpt2"
  generation_params:
    temperature: 0.8
    max_new_tokens: 30

training_args:
  output_dir: "trained_models/<<group_name>>/<<job_name>>"
  overwrite_output_dir: true
  num_train_epochs: 1  # Quick training for demo
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  logging_steps: 5
  evaluation_strategy: "epoch"
  save_strategy: "epoch"

max_length: 128  # Shorter for demo
train_test_split: 0.7
