name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Cache Poetry dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --no-root
        pip install pre-commit coverage pytest

    - name: Run pre-commit checks
      run: pre-commit run --all-files

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage report --fail-under=90
